-- Create facts table
CREATE TABLE IF NOT EXISTS facts (
    id SERIAL PRIMARY KEY,
    content TEXT NOT NULL,
    category VARCHAR(50) NOT NULL,
    source VARCHAR(100) NOT NULL,
    active BOOLEAN DEFAULT true,
    display_date DATE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Create related_articles table
CREATE TABLE IF NOT EXISTS related_articles (
    id SERIAL PRIMARY KEY,
    fact_id INTEGER REFERENCES facts(id),
    title VARCHAR(200) NOT NULL,
    url TEXT NOT NULL,
    source VARCHAR(100) NOT NULL,
    snippet TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
